services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8180:8080"
    command: start-dev
    restart: unless-stopped
